### ISSUE TITLE
IE11 doesn't pass all unittests

### ISSUE THREAD

**Issue by lygstate** [aaronpowell/db.js#115]
IE 11.0.0 (Windows 7) index.multiEntry should query for data in a multiEntry index FAILED
        Expected 0 to equal 3.
           at Anonymous function (C:/CI-Cor/kexin/db.js/tests/specs/query.js:689:21)
           at Anonymous function (C:/CI-Cor/kexin/db.js/bower/es6-shim/es6-shim.js:1706:11)
           at Anonymous function (C:/CI-Cor/kexin/db.js/bower/es6-shim/es6-shim.js:1679:13)
        Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
IE 11.0.0 (Windows 7) index.multiEntry should query for all data in a multiEntry index FAILED
        Expected 0 to equal 10.
           at Anonymous function (C:/CI-Cor/kexin/db.js/tests/specs/query.js:704:21)
           at Anonymous function (C:/CI-Cor/kexin/db.js/bower/es6-shim/es6-shim.js:1706:11)
           at Anonymous function (C:/CI-Cor/kexin/db.js/bower/es6-shim/es6-shim.js:1679:13)

**Comment by aaronpowell** [comment]
Yes, this is because IE doesn't support compound or multi key indexes. Adding this support to db.js would be an overhead I don't think I can/want to maintain. Instead there is a shim for it that can be an opt-in for when it's needed - https://github.com/dfahlander/idb-iegap
